[package]
name = "md5_phone_collision"
version = "0.1.0"
authors = ["Logan Saso <logansaso@gmail.com>"]
edition = "2018"

[dependencies]
md5 = "0.6.1"
hex-slice = "0.1.4"
rayon = "1.0.3"
crossbeam-channel = "0.3.8"
